version: "3.7"

#define service yang dijalankan yaitu : order, shipping, dan rabbitmq
services:
  #service order
  order:
    image: ghcr.io/danurwijayanto/order:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  #service shipping
  shipping:
    image: ghcr.io/danurwijayanto/shipping:latest
    restart: always
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
  #service rabbitmq
  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
